# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 06:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20160306_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.FileField(default=datetime.datetime(2016, 3, 25, 6, 41, 22, 966118, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
