# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='no image available for this post', upload_to=b''),
        ),
    ]
